# -*- coding: utf-8 -*-
"""SVR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yyCK4phdV7C7J1m_yvxx2Ymy7fqAWArQ

# Support Vector Regression /  Destek Vektör Regresyonu
"""

#küpütphaneler aktifleştirilir
import numpy as np
import pandas as pd 
from sklearn.model_selection import train_test_split, GridSearchCV,cross_val_score
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt
from sklearn.preprocessing import scale 
from sklearn import model_selection

from warnings import filterwarnings
filterwarnings('ignore')

#veriler okunur ve test ve eğitim için ayrılır
hit = pd.read_csv("Hitters.csv")
df = hit.copy()
df = df.dropna()
dms = pd.get_dummies(df[['League', 'Division', 'NewLeague']])
y = df["Salary"]
X_ = df.drop(['Salary', 'League', 'Division', 'NewLeague'], axis=1).astype('float64')
X = pd.concat([X_, dms[['League_N', 'Division_W', 'NewLeague_N']]], axis=1)
X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    test_size=0.25, 
                                                    random_state=42)

#veriler data frame formuna çevrilir
X_train = pd.DataFrame(X_train["Hits"])
X_test = pd.DataFrame(X_test["Hits"])

from sklearn.svm import SVR

#model fit edilir
svr_model = SVR("linear").fit(X_train, y_train)

#tehmin değerileri alınır
svr_model.predict(X_train)[0:5]

#svr modelini formulize edilmiş hali yazılır
print ("y = {0} + {1} x".format(svr_model.intercept_[0], 
                                svr_model.coef_[0][0]))

X_train["Hits"][0:1]

"""Yukarıdaki çıktıdan ilk eğitim verisinin 91 olduğunu anlıyoruz. Tahmin işleminde de ilk veri için sonucun 403.52 olduğunu bulmuştuk. Az önce bastırdığımız formül ile bu değerleri bir deneyelim!"""

-48.69756097561513 + 4.969512195122093*91

"""Görüldüğü üzere aynı sonuca ulaştık"""

y_pred = svr_model.predict(X_train)

plt.scatter(X_train, y_train)
plt.plot(X_train,y_pred, color = "r")

svr_model.predict([[91]])